import React from "react";
import { Link } from "react-router-dom";
import { CONSTRUCTION_CONFIG } from "../config/constructionConfig";

export const TermsPage: React.FC = () => {
  return (
    <div className="bg-surface-dim min-h-screen pb-20">
      {/* Header Banner */}
      <section className="bg-primary text-white py-14 sm:py-20 relative overflow-hidden border-b border-white/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 relative z-10">
          <div className="flex items-center gap-2 text-xs font-mono tracking-wider text-secondary uppercase mb-3">
            <Link to="/" className="text-white/60 hover:text-white transition-colors">Home</Link>
            <span>/</span>
            <span className="text-secondary">Legal</span>
          </div>

          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-secondary/20 text-secondary border border-secondary/30 text-xs font-mono uppercase tracking-wider mb-4">
            Construction Governance & Engineering Contract Terms
          </span>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-white mb-4">
            Terms of Service & Turnkey Agreement Standards
          </h1>
          <p className="text-sm sm:text-base text-white/70 leading-relaxed font-mono">
            RERA Karnataka Reference: {CONSTRUCTION_CONFIG.reraNumber} • GSTIN: {CONSTRUCTION_CONFIG.gstin}
          </p>
        </div>
      </section>

      {/* Terms Body */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <div className="bg-surface rounded-2xl border border-outline-variant p-6 sm:p-10 space-y-8 text-on-surface-variant text-sm sm:text-base leading-relaxed">
          <div>
            <h2 className="text-xl font-bold text-primary mb-3">1. Scope of Online Estimator</h2>
            <p>
              Estimates generated by the SK Constructions online calculator are preliminary engineering projections based on current Bangalore market rates for TMT steel (Fe-550D) and Ready-Mix Concrete (M25/M30). Final contract amounts are confirmed following formal soil test core sampling, BBMP/BDA sanctioned plan verification, and site contour leveling.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-primary mb-3">2. Fixed Price & Zero Escalation Clause</h2>
            <p>
              Once a Turnkey Residential Construction Agreement is executed, the agreed rate per sq.ft is legally locked against inflation. Material price escalations (cement or steel market fluctuations) during the contractual build timeline are absorbed 100% by SK Constructions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-primary mb-3">3. Milestone-Linked Escrow Safeguards</h2>
            <p>
              All client payments are held in milestone escrow accounts managed via scheduled commercial banks. Funds are released exclusively upon digital sign-off of quality audit stages (e.g. Plinth completion, 1st Slab Pour, Brickwork, Plastering, MEP handoff) backed by slump cone and compressive strength lab reports.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-primary mb-3">4. 10-Year Structural Warranty</h2>
            <p>
              SK Constructions provides a registered 10-year warranty covering foundation stability, RCC column/beam load distribution, and structural crack prevention in accordance with IS 456:2000. Waterproofing carries an independent 5-year chemical bond warranty.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-primary mb-3">5. Jurisdiction & Dispute Resolution</h2>
            <p>
              Any disputes arising from turnkey contracts or consultancy services shall be subject to the exclusive jurisdiction of the competent courts in Bangalore, Karnataka, and governed by the Arbitration and Conciliation Act, 1996 of India.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};
